pull_request_rules:
  - name: instruct bors to merge dependabot PRs with passing tests
    conditions:
      - "status-success=ci (1.40.0)"
      - "status-success=ci (stable)"
      - "author:dependabot-preview[bot]"
    actions:
      comment:
        message: "bors r+"
  - name: instruct bors to merge PRs with passing tests and 2 approvals
    conditions:
      - "status-success=ci (1.40.0)"
      - "status-success=ci (stable)"
      - "status-success=license/cla"
      - "#approved-reviews-by>=2"
      - label!=work-in-progress
      - label!=blocked
      - label!=no-mergify
      - head~=^(?!release.*).*$
      - "#changes-requested-reviews-by=0"
    actions:
      comment:
        message: "bors r+"
  - name: Delete branch if the pull request is merged
    conditions:
      - merged
    actions:
      delete_head_branch:
