language: rust
rust:
  - stable
  - nightly
cache:
  cargo: true
sudo: required
install: true
services: docker
before_script:
  - rustup component add rustfmt
script:
  - cargo fmt -- --check
  - cargo test --all
notifications:
  email: false
  slack:
    rooms:
    - tenx-company:buMm6Pg6Sbhljx2HRLwNC44z#coblox-bots
    on_success: never
    on_failure: always
    on_pull_requests: true
