[package]
name = "blockchain_contracts"
version = "0.1.0"
authors = ["CoBloX developers <team@coblox.tech>"]
edition = "2018"

[dependencies]
web3 = "=0.5.0"
serde = { version = "1.0", features = ["derive"] }
binary_macros = "0.6"
hex = "0.3"

[build-dependencies]
regex = "1.1"
