version: 2.1
workflows:
  version: 2
  main:
    jobs:
      - beta-test
      - stable-test

jobs:
  stable-test:
    working_directory: ~/workspace
    machine:
      image: ubuntu-1604:201903-01
    environment:
      - RUST_TEST_THREADS: "8"
      - RUST_TOOLCHAIN: "beta"
    steps:
      - checkout
      - install_rust
      - install_sccache
      - restore_sccache_cache
      - run:
          name: "Beta Build & Test"
          command: |
            make ci
      - save_sccache_cache
  beta-test:
    working_directory: ~/workspace
    machine:
      image: ubuntu-1604:201903-01
    environment:
      - RUST_TEST_THREADS: "8"
      - RUST_TOOLCHAIN: "beta"
    steps:
      - checkout
      - install_rust
      - install_sccache
      - restore_sccache_cache
      - run:
          name: "Stable Build & Test"
          command: |
            make ci
      - save_sccache_cache
commands:
  install_rust:
    steps:
      - run:
          name: "Install Rust"
          command: |
            curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain ${RUST_TOOLCHAIN}
            source $HOME/.cargo/env
            echo 'export PATH=$HOME/.cargo/bin:$PATH' >> $BASH_ENV
            rustup run ${RUST_TOOLCHAIN} rustc --version --verbose
            rustup run ${RUST_TOOLCHAIN} cargo --version --verbose
  install_sccache:
    steps:
      - run:
          name: "Install sccache"
          command: |
            cargo install sccache
            echo 'export "RUSTC_WRAPPER"="sccache"' >> $BASH_ENV
            echo 'export "SCCACHE_CACHE_SIZE"="1G"' >> $BASH_ENV
            sccache --version
  restore_sccache_cache:
    steps:
      - restore_cache:
          name: "Restore sccache cache"
          key: sccache-cache-${RUST_TOOLCHAIN}-{{ arch }}-{{ .Environment.CIRCLE_JOB }}
  save_sccache_cache:
    steps:
      - save_cache:
          name: "Save sccache cache"
          # We use {{ epoch }} to always upload a fresh cache:
          # Of course, restore_cache will not find this exact key,
          # but it will fall back to the closest key (aka the most recent).
          # See https://discuss.circleci.com/t/add-mechanism-to-update-existing-cache-key/9014/13
          key: sccache-cache-${RUST_TOOLCHAIN}-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ epoch }}
          paths:
            - "~/.cache/sccache"
