version: 1
update_configs:
  - package_manager: "rust:cargo"
    directory: "/"
    update_schedule: "daily"
    default_labels:
      - "dependencies"
    allowed_updates:
      - match:
          update_type: "all"
          dependency_type: "direct"
    ignored_updates:
      # primitive-types is a transitive dependency of web3, need to update it in lockstep
      - match:
          dependency_name: "primitive-types"
      # rlp is a transitive dependency of web3, need to update it in lockstep
      - match:
          dependency_name: "rlp"
